### ISSUE TITLE
IOS点击蜡烛闪退

### ISSUE THREAD

**Issue by antgodev** [472647301/react-native-kline#1]
如题

**Comment by 472647301** [comment]
我文档还没补全，iOS需要add KLineInfoView.xib 到Copy Bundle resources

**Comment by 472647301** [comment]
文档已更新

**Comment by antgodev** [comment]
Installing react-native-kline 2.0.3 (was 2.0.1)
还是闪退

**Comment by 472647301** [comment]
麻烦贴一下报错信息 ------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;AntGo&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年9月30日(星期三) 晚上7:08
收件人:&nbsp;&quot;472647301/react-native-kline&quot;<react-native-kline@noreply.github.com&gt;;
抄送:&nbsp;&quot;秃尾巴的猫&quot;<472647301@qq.com&gt;;&quot;State change&quot;<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [472647301/react-native-kline] IOS点击蜡烛闪退 (#1)
