### ISSUE TITLE
locales issue

### ISSUE THREAD

**Issue by yousef-zeiad** [472647301/react-native-kline#13]
I'm facing the locales issue i cant change the language to English can you please provide how we can do it.

**Comment by volodya-korol** [comment]
@yousef-zeiad hello, have you found a way to change the language to English or add custom language

**Comment by yousef-zeiad** [comment]
> @yousef-zeiad hello, have you found a way to change the language to English or add custom language

yeah all you need is to pass an array with the strings locales=['Time',......]
