### ISSUE TITLE
运行没数据

### ISSUE THREAD

**Issue by HimiGame** [472647301/react-native-kline#7]
只有一个黑色背景

**Comment by 472647301** [comment]
我服务器的接口挂了，你需要替换成别的接口------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年4月19日(星期一) 晚上9:25
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[472647301/react-native-kline] 运行没数据 (#7)

**Comment by HimiGame** [comment]
> 我服务器的接口挂了，你需要替换成别的接口------------------&nbsp;原始邮件&nbsp;------------------ ***@***.***&gt; 发送时间:&nbsp;2021年4月19日(星期一) 晚上9:25 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[472647301/react-native-kline] 运行没数据 (#7)

有没有别的接口地址能使用？ 想看看数据格式来着  拜托啦

**Comment by 472647301** [comment]
demo已替换成ok接口
